### ISSUE TITLE
Shake Module issue with 'FadeOutTime'

### ISSUE THREAD

**Issue by Motofied** [Sleitnick/RbxUtil#102] opened 2022-07-07 19:32 UTC
Whenever FadeOutTime is set to 0 the last shake frame is always returning infinite or 'nan' for the position

https://gyazo.com/d0325e6c40cef831aeb39957bc29ff14

![image](https://user-images.githubusercontent.com/68410425/177857115-fea9cf6a-6982-4fda-a2f0-f74da1620550.png)

![image](https://user-images.githubusercontent.com/68410425/177857134-2036733c-5f53-495b-8944-cca9f928d2f2.png)

**Comment by Sleitnick** [comment] 2022-07-07 23:10
Thanks for the report! This is fixed in `v0.1.6`.

**Closed** 2022-07-07 23:10 UTC
Labels: bug

**Comment by Sleitnick** [comment] 2022-07-07 23:12
For historical purposes:
The issue was caused by dividing by zero. This occurred when the Shake instance tried to fade out when the fade duration was set to 0. This has been fixed by simply checking for a 0-value on the fade-out step and skipping the calculation if found to be 0.
